/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/admin/failures': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List recent collection failures */
		get: operations['getApiAdminFailures'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/admin/watermarks': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List metric watermarks */
		get: operations['getApiAdminWatermarks'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/metrics': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List metrics */
		get: operations['getApiMetrics'];
		put?: never;
		/** Create metric */
		post: operations['postApiMetrics'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/releases/{releaseID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get release by ID */
		get: operations['getApiReleasesByReleaseID'];
		put?: never;
		post?: never;
		/** Delete release */
		delete: operations['deleteApiReleasesByReleaseID'];
		options?: never;
		head?: never;
		/** Update release */
		patch: operations['patchApiReleasesByReleaseID'];
		trace?: never;
	};
	'/api/accounts/{accountID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get account by ID */
		get: operations['getApiAccountsByAccountID'];
		put?: never;
		post?: never;
		/** Delete account */
		delete: operations['deleteApiAccountsByAccountID'];
		options?: never;
		head?: never;
		/** Update account followers */
		patch: operations['patchApiAccountsByAccountID'];
		trace?: never;
	};
	'/api/admins/{adminID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Revoke admin access */
		delete: operations['deleteApiAdminsByAdminID'];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/vaults/{vaultID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get vault by ID */
		get: operations['getApiVaultsByVaultID'];
		put?: never;
		post?: never;
		/** Delete vault */
		delete: operations['deleteApiVaultsByVaultID'];
		options?: never;
		head?: never;
		/** Update token in vault */
		patch: operations['patchApiVaultsByVaultID'];
		trace?: never;
	};
	'/api/service-tokens/{tokenID}/revoke': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Revoke a webhook token */
		post: operations['postApiService-tokensByTokenIDRevoke'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/metrics/{metricID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get metric by ID */
		get: operations['getApiMetricsByMetricID'];
		put?: never;
		post?: never;
		/** Delete metric */
		delete: operations['deleteApiMetricsByMetricID'];
		options?: never;
		head?: never;
		/** Update metric */
		patch: operations['patchApiMetricsByMetricID'];
		trace?: never;
	};
	'/api/resources': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List resources */
		get: operations['getApiResources'];
		put?: never;
		/** Create resource */
		post: operations['postApiResources'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/vaults': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List vaults */
		get: operations['getApiVaults'];
		put?: never;
		/** Create vault */
		post: operations['postApiVaults'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/service-tokens': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List webhook tokens */
		get: operations['getApiService-tokens'];
		put?: never;
		/** Mint a webhook token */
		post: operations['postApiService-tokens'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/admin/queues': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Inspect queue and scheduler health */
		get: operations['getApiAdminQueues'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/resources/{resourceID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get resource by ID */
		get: operations['getApiResourcesByResourceID'];
		put?: never;
		post?: never;
		/** Delete resource */
		delete: operations['deleteApiResourcesByResourceID'];
		options?: never;
		head?: never;
		/** Update resource */
		patch: operations['patchApiResourcesByResourceID'];
		trace?: never;
	};
	'/api/service-tokens/rotate-key': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Rotate the signing key */
		post: operations['postApiService-tokensRotate-key'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/accounts': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List accounts */
		get: operations['getApiAccounts'];
		put?: never;
		/** Create account */
		post: operations['postApiAccounts'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/resources/{resourceID}/metrics': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Record a metric for one resource */
		post: operations['postApiResourcesByResourceIDMetrics'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/releases': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List releases */
		get: operations['getApiReleases'];
		put?: never;
		/** Create release */
		post: operations['postApiReleases'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/admins': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List admins */
		get: operations['getApiAdmins'];
		put?: never;
		/** Grant admin access */
		post: operations['postApiAdmins'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AccountPublic: {
			/** Format: int64 */
			followers?: number | null;
			resources?: components['schemas']['ResourcePublic'][] | null;
			/** Format: uuid */
			id?: string | null;
			vault?: components['schemas']['VaultPublic'];
			platform?: components['schemas']['Platform'];
			name?: string | null;
			/** Format: date-time */
			deletedAt?: string | null;
			/** Format: date-time */
			createdAt?: string | null;
			/** Format: date-time */
			updatedAt?: string | null;
		};
		VaultUpdate: {
			token: string;
			expires: components['schemas']['VaultExpires'];
		};
		/** @enum {string} */
		MetricType:
			| 'authentications'
			| 'clones'
			| 'deployments'
			| 'downloads'
			| 'forks'
			| 'likes'
			| 'pulls'
			| 'stars'
			| 'subscribers'
			| 'views'
			| 'authenticationsAllTime'
			| 'clonesAllTime'
			| 'downloadsAllTime'
			| 'pullsAllTime'
			| 'viewsAllTime';
		JobFailureInsight: {
			identifier: string;
			job: string;
			severity: string;
			details: string;
			/** Format: uuid */
			accountID?: string | null;
			/** Format: uuid */
			resourceID?: string | null;
			/** Format: uuid */
			id?: string | null;
			subject: string;
			/** Format: date-time */
			failedAt: string;
		};
		MetricPublic: {
			/** Format: double */
			reading?: number | null;
			type?: components['schemas']['MetricType'];
			/** Format: uuid */
			id?: string | null;
			/** Format: uuid */
			resourceID?: string | null;
			/** Format: date-time */
			recordedAt?: string | null;
		};
		ServiceTokenCreate: {
			/** Format: uuid */
			resourceID: string;
			/** Format: int64 */
			expiresInDays?: number | null;
			label: string;
		};
		/** @enum {string} */
		ResourceType:
			'agent' | 'container' | 'dataset' | 'model' | 'package' | 'repository' | 'service';
		ReleaseUpdate: {
			/** Format: int64 */
			year?: number | null;
			version?: string | null;
			/** Format: int64 */
			month?: number | null;
		};
		VaultExpires: {
			/** Format: int64 */
			year: number;
			/** Format: int64 */
			day: number;
			/** Format: int64 */
			month: number;
		};
		MetricCreateForResource: {
			/** Format: double */
			reading: number;
			type: components['schemas']['MetricType'];
		};
		QueueInsight: {
			/** Format: date-time */
			schedulerLastSeenAt?: string | null;
			/** Format: int64 */
			processing: number;
			/** Format: int64 */
			pending: number;
			schedulerState: string;
			queue: string;
		};
		ReleaseCreate: {
			/** Format: int64 */
			year: number;
			/** Format: uuid */
			resourceID: string;
			version: string;
			/** Format: int64 */
			month: number;
		};
		MetricUpdate: {
			/** Format: double */
			reading?: number | null;
			type?: components['schemas']['MetricType'];
		};
		AccountUpdate: {
			/** Format: int64 */
			followers?: number | null;
		};
		WatermarkInsight: {
			/** Format: date-time */
			updatedAt?: string | null;
			/** Format: uuid */
			resourceID: string;
			resourceName: string;
			/** Format: uuid */
			id?: string | null;
			/** Format: date-time */
			countedThrough: string;
			type: components['schemas']['MetricType'];
		};
		MetricCreate: {
			/** Format: double */
			reading: number;
			/** Format: uuid */
			resourceID: string;
			type: components['schemas']['MetricType'];
		};
		ResourceUpdate: {
			/** Format: int64 */
			collectionIntervalDays?: number | null;
			name?: string | null;
			type?: components['schemas']['ResourceType'];
		};
		AdminCreate: {
			username: string;
		};
		ResourcePublic: {
			/** Format: int64 */
			collectionIntervalDays?: number | null;
			/** Format: date-time */
			updatedAt?: string | null;
			/** Format: uuid */
			accountID?: string | null;
			releases?: components['schemas']['ReleasePublic'][] | null;
			/** Format: uuid */
			id?: string | null;
			links?: components['schemas']['ResourceResourceLink'][] | null;
			/** Format: date-time */
			createdAt?: string | null;
			name?: string | null;
			metrics?: components['schemas']['MetricPublic'][] | null;
			/** Format: date-time */
			deletedAt?: string | null;
			/** Format: date-time */
			nextCollectionAt?: string | null;
			type?: components['schemas']['ResourceType'];
		};
		ServiceTokenPublic: {
			/** Format: date-time */
			createdAt?: string | null;
			/** Format: uuid */
			resourceID?: string | null;
			/** Format: uuid */
			id?: string | null;
			/** Format: date-time */
			expiresAt?: string | null;
			/** Format: uuid */
			jti?: string | null;
			/** Format: date-time */
			revokedAt?: string | null;
			label?: string | null;
		};
		ResourceResourceLink: {
			platform?: components['schemas']['Platform'];
			/** Format: uuid */
			id?: string | null;
			name?: string | null;
		};
		ReleasePublic: {
			/** Format: uuid */
			id?: string | null;
			version?: string | null;
			/** Format: uuid */
			resourceID?: string | null;
			/** Format: date-time */
			releasedAt?: string | null;
		};
		VaultCreate: {
			/** Format: uuid */
			accountID: string;
			token: string;
			expires: components['schemas']['VaultExpires'];
		};
		VaultPublic: {
			/** Format: date-time */
			updatedAt?: string | null;
			/** Format: uuid */
			accountID?: string | null;
			/** Format: date-time */
			expiresAt?: string | null;
			/** Format: date-time */
			createdAt?: string | null;
			/** Format: uuid */
			id?: string | null;
			name?: string | null;
		};
		AdminPublic: {
			username?: string | null;
			/** Format: date-time */
			createdAt?: string | null;
			addedBy?: string | null;
			/** Format: uuid */
			id?: string | null;
			isRoot?: boolean | null;
		};
		AccountCreate: {
			name: string;
			platform: components['schemas']['Platform'];
		};
		ResourceCreate: {
			/** Format: uuid */
			accountID: string;
			/** Format: int64 */
			collectionIntervalDays?: number | null;
			name: string;
			type: components['schemas']['ResourceType'];
		};
		/** @enum {string} */
		Platform: 'github' | 'ghcr' | 'huggingface' | 'npm' | 'pypi' | 'patra';
		ServiceTokenControllerRotatedKey: {
			activeKid: string;
			message: string;
		};
		ServiceTokenMinted: {
			token: string;
			endpoint: string;
			serviceToken: components['schemas']['ServiceTokenPublic'];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getApiAdminFailures: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['JobFailureInsight'][];
				};
			};
		};
	};
	getApiAdminWatermarks: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WatermarkInsight'][];
				};
			};
		};
	};
	getApiMetrics: {
		parameters: {
			query?: {
				resourceID?: string | null;
				type?: components['schemas']['MetricType'];
				limit?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MetricPublic'][];
				};
			};
		};
	};
	postApiMetrics: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['MetricCreate'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MetricPublic'];
				};
			};
		};
	};
	getApiReleasesByReleaseID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				releaseID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ReleasePublic'];
				};
			};
		};
	};
	deleteApiReleasesByReleaseID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				releaseID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: never;
	};
	patchApiReleasesByReleaseID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				releaseID: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ReleaseUpdate'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ReleasePublic'];
				};
			};
		};
	};
	getApiAccountsByAccountID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				accountID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AccountPublic'];
				};
			};
		};
	};
	deleteApiAccountsByAccountID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				accountID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: never;
	};
	patchApiAccountsByAccountID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				accountID: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AccountUpdate'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AccountPublic'];
				};
			};
		};
	};
	deleteApiAdminsByAdminID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				adminID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: never;
	};
	getApiVaultsByVaultID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				vaultID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VaultPublic'];
				};
			};
		};
	};
	deleteApiVaultsByVaultID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				vaultID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: never;
	};
	patchApiVaultsByVaultID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				vaultID: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['VaultUpdate'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VaultPublic'];
				};
			};
		};
	};
	'postApiService-tokensByTokenIDRevoke': {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tokenID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceTokenPublic'];
				};
			};
		};
	};
	getApiMetricsByMetricID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				metricID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MetricPublic'];
				};
			};
		};
	};
	deleteApiMetricsByMetricID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				metricID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: never;
	};
	patchApiMetricsByMetricID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				metricID: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['MetricUpdate'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MetricPublic'];
				};
			};
		};
	};
	getApiResources: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ResourcePublic'][];
				};
			};
		};
	};
	postApiResources: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ResourceCreate'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ResourcePublic'];
				};
			};
		};
	};
	getApiVaults: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VaultPublic'][];
				};
			};
		};
	};
	postApiVaults: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['VaultCreate'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VaultPublic'];
				};
			};
		};
	};
	'getApiService-tokens': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceTokenPublic'][];
				};
			};
		};
	};
	'postApiService-tokens': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ServiceTokenCreate'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceTokenMinted'];
				};
			};
		};
	};
	getApiAdminQueues: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['QueueInsight'];
				};
			};
		};
	};
	getApiResourcesByResourceID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resourceID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ResourcePublic'];
				};
			};
		};
	};
	deleteApiResourcesByResourceID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resourceID: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: never;
	};
	patchApiResourcesByResourceID: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resourceID: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ResourceUpdate'];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ResourcePublic'];
				};
			};
		};
	};
	'postApiService-tokensRotate-key': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ServiceTokenControllerRotatedKey'];
				};
			};
		};
	};
	getApiAccounts: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AccountPublic'][];
				};
			};
		};
	};
	postApiAccounts: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AccountCreate'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AccountPublic'];
				};
			};
		};
	};
	postApiResourcesByResourceIDMetrics: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resourceID: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['MetricCreateForResource'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['MetricPublic'];
				};
			};
		};
	};
	getApiReleases: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ReleasePublic'][];
				};
			};
		};
	};
	postApiReleases: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ReleaseCreate'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ReleasePublic'];
				};
			};
		};
	};
	getApiAdmins: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AdminPublic'][];
				};
			};
		};
	};
	postApiAdmins: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['AdminCreate'];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['AdminPublic'];
				};
			};
		};
	};
}
