@host=localhost:8080
@accountId=0ba5c0de-0000-0000-0000-000000000000

###

# @name createResource
POST /resources HTTP/1.1
HOST: {{host}}
Content-Type: application/json

{
    "accountID": "{{accountId}}",
    "name": "gnnfoodflowportal",
    "type": "repository"
}

###

POST /releases HTTP/1.1
HOST: {{host}}
Content-Type: application/json

{
    "resourceID": "{{createResource.response.body.$.id}}",
    "version": "1.0.0",
    "month": 8,
    "year": 2025
}

###

POST /releases HTTP/1.1
HOST: {{host}}
Content-Type: application/json

{
    "resourceID": "{{createResource.response.body.$.id}}",
    "version": "1.1.0",
    "month": 10,
    "year": 2025
}

###

POST /releases HTTP/1.1
HOST: {{host}}
Content-Type: application/json

{
    "resourceID": "{{createResource.response.body.$.id}}",
    "version": "1.2.0",
    "month": 5,
    "year": 2026
}

###

POST /metrics HTTP/1.1
HOST: {{host}}
Content-Type: application/json

{
    "resourceID": "{{createResource.response.body.$.id}}",
    "reading": 110,
    "type": "clones"
}

###

POST /metrics HTTP/1.1
HOST: {{host}}
Content-Type: application/json

{
    "resourceID": "{{createResource.response.body.$.id}}",
    "reading": 38,
    "type": "views"
}

###
